---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2.7'
      raw: sudo apt-get -y install python


- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: add ssh key
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: 0600

- name: Install and configure nginx
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  roles:
   - nginx

- name: Install and configure minio
  hosts: all
  become_user: root
  become_method: sudo
  become: true
  roles:
     - minio
